
spring:
  application:
    name: eTicaretSitesi
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: zeynepzorbozan
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  graphql:
    graphiql:
      enabled: true
    http:
      path: /graphql
server:
  port: 8000

jwt:
  secret: Qm9yN2xYV2R4TnJzVjVhSzJQeEZtY0p4OE5iU3dLdFlwUmhWcUZnWA==
  access-expiration: 3600000
  refresh-expiration: 604800000

