
spring:
  application:
    name: eTicaretSitesi
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: zeynepzorbozan
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  graphql:
    graphiql:
      enabled: true
    http:
      path: /graphql
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
server:
  port: 8000

file-service:
  url: http://localhost:8001

mail:
  from: ${MAIL_FROM:${MAIL_USERNAME}}

jwt:
  secret: Qm9yN2xYV2R4TnJzVjVhSzJQeEZtY0p4OE5iU3dLdFlwUmhWcUZnWA==
  access-expiration: 3600000
  refresh-expiration: 604800000

