
spring:
  application:
    name: eTicaretSitesi
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: zeynepzorbozan
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  graphql:
    graphiql:
      enabled: true
    http:
      path: /graphql
server:
  port: 8000

jwt:
  secret: 1234567890123456789012345678901234567890123456789012345678901234
  expiration: 3600000